
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kimochi3_development

test:
  <<: *default
  database: kimochi3_test

production:
  <<: *default
  database: kimochi3_production
  username: kimochi3
  password: <%= ENV["KIMOCHI3_DATABASE_PASSWORD"] %>
